---
title: "district_stats"
author: "Owen Liu"
date: "April 19, 2016"
output: html_document
---

```{r packages and useful functions, echo=FALSE}
library(gclus)
library(dplyr)
#### panelutils.R ####
#
# License: GPL-2 
# Author: Francois Gillet, 23 August 2012
#
## Put Pearson, Spearman or Kendall correlations on the upper panel
panel.cor <- function(x, y, method="pearson", digits=3, cex.cor=1.2, no.col=FALSE)
{
	usr <- par("usr"); on.exit(par(usr))
	par(usr = c(0, 1, 0, 1))
	r <- cor(x, y, method=method)
	ra <- cor.test(x, y, method=method)$p.value
	txt <- round(r, digits)
	prefix <- ""
	if(ra <= 0.1) prefix <- "."
	if(ra <= 0.05) prefix <- "*"
	if(ra <= 0.01) prefix <- "**"
	if(ra <= 0.001) prefix <- "***"
	if(no.col)
	{
		color <- 1
		if(r < 0) { if(ra <= 0.001) sig <- 4 else sig <- 3 }
		else { if(ra <= 0.001) sig <- 2 else sig <- 1 }
	}
	else
	{
		sig <- 1
		if(ra <= 0.001) sig <- 2
		color <- 2
		if(r < 0) color <- 4
	}
	txt <- paste(txt, prefix, sep="\n")
	text(0.5, 0.5, txt, cex = cex.cor, font=sig, col=color)
}
 
 
## Put histograms on the diagonal
panel.hist <- function(x, no.col=FALSE, ...)
{
	usr <- par("usr"); on.exit(par(usr))
	par(usr = c(usr[1:2], 0, 1.5) )
	his <- hist(x, plot=FALSE)
	breaks <- his$breaks; nB <- length(breaks)
	y <- his$counts
	y <- y/max(y)
	if(no.col) rect(breaks[-nB], 0, breaks[-1], y, col="gray", ...)
	else rect(breaks[-nB], 0, breaks[-1], y, col="cyan", ...)
}
 
 
## Add black lowess curves to scatter plots
panel.smoothb <- function (x, y, col=par("col"), bg=NA, pch=par("pch"), 
	cex=1, col.smooth="black", span=2/3, iter=3, ...) 
{
	points(x, y, pch=pch, col=col, bg=bg, cex=cex)
	ok <- is.finite(x) & is.finite(y)
	if (any(ok)) 
	lines(stats::lowess(x[ok], y[ok], f=span, iter=iter), col=col.smooth, ...)
}
 
 
#Usage:
#pairs(num.mat, lower.panel=panel.smooth, upper.panel=panel.cor, diag.panel=panel.hist)
#pairs(num.mat, lower.panel=panel.smooth, upper.panel=panel.cor, method="kendall")
```

Import the dataset:

```{r data import}
W_D <- getwd()
wd.dat.3reg <- read.csv(file=paste(W_D,'/data/wd_final_28Apr2016.csv',sep=""))

# fix variable names for easier calls later (depends on version of data, CHECK THIS)
wd.dat.3reg<-wd.dat.3reg[,-1]
names(wd.dat.3reg) <- c('pwsid','district','severity','simpson','ground','surf','imported','recycled','desal','tot.source','propground','propsurf','propdesal','proprecyc','propbank','propimport','casgem','adj','totgpcd15','rgpcd15','totgpcd10','rgpcd10','changetot','changer','medinc','buyertier','sellertier','buyers','sellers','region')
wd.dat.3reg$medinc<-wd.dat.3reg$medinc/1000
wd.dat.3reg$district <- as.character(wd.dat.3reg$district)
sapply(names(wd.dat.3reg),function(x)class(wd.dat.3reg[,x])) # are all variables correctly classified?

# 3 region districts (UPDATED 5.18.16)
three.reg <- read.csv(file=paste(W_D,'/data/wd_3_reg.csv',sep=""))
three.reg <- three.reg[-2] # remove name column
names(three.reg) <- c('pwsid','region2')
wd.dat.3reg<- left_join(wd.dat.3reg,three.reg,by=c("pwsid"))

# Jose's district use stats, updated 5.24.16 (per capita, total, and population)
rgpcd <- read.csv(file=paste0(W_D,'/data/changeData_PWSID_gpcd.csv'),stringsAsFactors = F)
names(rgpcd) <- c('pwsid',"district","totgpcd10","rgpcd10","totgpcd15","rgpcd15","changetot.gpcd","changer.gpcd")
rgpcd.miss<- apply(rgpcd,2,function(x)sum(is.na(x))) # How many NAs for each variable?
rgpcd.miss.names <-data.frame(pwsid=rgpcd$pwsid[is.na(rgpcd$changer.gpcd)],name=rgpcd$district[is.na(rgpcd$changer.gpcd)]) # which are missing change data?

totg <- read.csv(file=paste0(W_D,'/data/changeData_PWSID_tot.csv'),stringsAsFactors = F)
names(totg) <- c('pwsid',"district","tot10.g","r10.g","tot15.g","r15.g","changetot.g","changer.g","changetot.g.pcnt","changer.g.pcnt")
totg.miss<-apply(totg,2,function(x)sum(is.na(x))) # How many NAs for each variable?
totg.miss.names<-data.frame(pwsid=totg$pwsid[is.na(totg$changer.g)],name=totg$district[is.na(totg$changer.g)]) # which are missing change data?

wdpop <- read.csv(file=paste0(W_D,'/data/changeData_PWSID_pop.csv'),stringsAsFactors = F)
names(wdpop) <- c("pwsid","district","pop10","pop15")
wd.pop.miss<-apply(wdpop,2,function(x)sum(is.na(x))) # How many NAs for each variable?
wdpop.miss.names.10<-data.frame(pwsid=wdpop$pwsid[is.na(wdpop$pop10)],name=wdpop$district[is.na(wdpop$pop10)]) # which are missing pop data 2010?
wdpop.miss.names.15<-data.frame(pwsid=wdpop$pwsid[is.na(wdpop$pop15)],name=wdpop$district[is.na(wdpop$pop15)]) # which are missing pop data 2015?

## Jose's missing data, together
missing <- full_join(rgpcd.miss.names,totg.miss.names,by="pwsid") %>% full_join(wdpop.miss.names.10,by="pwsid") %>% full_join(wdpop.miss.names.15,by="pwsid")
names(missing) <- c("pwsid","changer.gpcd","changer.g","pop10","pop15")
write.csv(missing,file=paste0(W_D,"/data/missing_change_data_5.25.16.csv"))

## PWSID and District Name mismatches between current "master" and Jose's data
jose.not.master.pwsid <- data.frame(jnmid=setdiff(rgpcd$pwsid,wd.dat.3reg$pwsid))
write.csv(jose.not.master.pwsid,file=paste0(W_D,"/data/mismatches1.csv"))
jose.not.master.district <- data.frame(jnmd=setdiff(rgpcd$district,wd.dat.3reg$district))
write.csv(jose.not.master.district,file=paste0(W_D,"/data/mismatches2.csv"))
master.not.jose.pwsid <- data.frame(mnjid=setdiff(wd.dat.3reg$pwsid,rgpcd$pwsid))
write.csv(master.not.jose.pwsid,file=paste0(W_D,"/data/mismatches3.csv"))
master.not.jose.district <- data.frame(mnjd=setdiff(wd.dat.3reg$district,rgpcd$district))
write.csv(master.not.jose.district,file=paste0(W_D,"/data/mismatches4.csv"))


# remove old change data and add Jose's new data (5.24.16)
exc <- c("totgpcd15","rgpcd15","totgpcd10","rgpcd10","changetot","changer")
wd.dat.3reg<- select(wd.dat.3reg,-one_of(exc)) %>% inner_join(rgpcd,by=c("pwsid","district")) %>% inner_join(totg,by=c("pwsid","district")) %>% inner_join(wdpop,by=c("pwsid","district"))

# remove rows with zero in the change in use data

wd.dat.3reg <- dplyr::filter(wd.dat.3reg,!is.na(changer.gpcd),!is.na(changer.g),!is.na(pop10),!is.na(pop15))

#write.csv(wd.dat.3reg,file=paste(W_D,'/data/wd_dat_5_19.csv',sep=""))
```

Quick looks at the variables and their relationships

```{r prelim stats}
# attach(wd.dat.3reg)
# hist(roc_r)
# hist(population,breaks=15)
# hist(severity)
# hist(med_inc)
# hist(Number.of.Buyer.in.the.first.tier)
# hist(Number.of.Seller.in.the.first.tier)
# # subset of variables (to start with)
# c.vars <- names(wd.dat.3reg)[c(6:20,35:36)]
# vars <- wd.dat.3reg[,c.vars]
# i.vars <- c.vars[c(1:15,17)]
# #correlations (Pearson's r)
# vars.pearson <- cor(wd.dat.3reg[c.vars])
# round(vars.pearson,2)
# 
# #ordered for plotting
# vars.o <- order.single(vars.pearson)
# op <- par(mfrow=c(1,1),pty="s")
# pairs(vars[,vars.o], lower.panel=panel.smooth,upper.panel=panel.cor, diag.panel=panel.hist, main="Pearson Correlation Matrix")
# par(op)
# 
# # lm for rate of change
# summary(lm(formula=paste("roc_r ~ ",paste(i.vars, collapse="+"),sep = ""), data=vars, na.action = na.exclude))
# # very crudely, the significant effects that pop out are:
# # median income (+)
# # recycled (+)
# # proportion groundwater (-)
# 
# plot(severity, roc_r, pch=20, xlab="Cumulative Weeks over Drought Level 3 since January 2013",
#    ylab="Percent Change in Residential Water Use, 2010-2015", main="Severity vs. Change in Use")
# lines(loess.smooth(severity,roc_r),col="red")
# abline(h=0,lty="dotted")
# abline(v=0,lty="dotted")
# 
# plot(med_inc,roc_r, pch=20, main="Median Income vs. Residential Rate of Change in Water Use", xlab="Median Household Income",ylab="Percent Change in Per Capita Use, 2010-2015")
# abline(lm(roc_r~med_inc),col="red")
# text(150000,20,paste('Adj R2 = ',round(summary(lm(roc_r~med_inc))$adj.r.squared,4)),col='red')
# text(150000,10,paste("p-value = ",round(summary(lm(roc_r~med_inc))$coefficients['med_inc','Pr(>|t|)'],4)),col="blue")
# abline(h=0,lty="dotted")
# text(med_inc,roc_r,labels=as.character(pwsname),cex=0.5)
# 
# rocr.inc <- data.frame(pwsid=pwsid,pwsname=as.character(pwsname),roc_r=roc_r,med_inc=med_inc)
```

Scatter plots by region for all major variables

```{r scatterplots}
attach(wd.dat.3reg)
require(ggplot2)
# for all scatterplots for now, the y-variable(dependent variable) is change in use (total), variable changetot
# Continuous variables are severity, simpson, propground,propsurf,proprecyc,propimport,medinc,totgpcd15
#Severity
ggplot(data=wd.dat.3reg,aes(x=severity,y=changer,col=region2)) + geom_point() +geom_smooth(method=lm,se=FALSE) + ggtitle("Drought Severity vs. Change in Residential Use") +xlab("Severity(Weeks at or Above Drought Monitor Category 3)") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("severity.png")
#Simpson
ggplot(data=wd.dat.3reg,aes(x=simpson,y=changer,col=region2)) + geom_point() +geom_smooth(method=lm,se=FALSE) + ggtitle("Source Diversity vs. Change in Residential Use") +xlab("Diversity of Sources (Simpson index)") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("simpson.png")
#propground
ggplot(data=wd.dat.3reg,aes(x=propground,y=changer,col=region2)) + geom_point() +geom_smooth(method=lm,se=FALSE) + ggtitle("Proportion Groundwater vs. Change in Residential Use") +xlab("Proportion Groundwater") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("propground.png")
#propsurf
ggplot(data=wd.dat.3reg,aes(x=propsurf,y=changer,col=region2)) + geom_point() +geom_smooth(method=lm,se=FALSE) + ggtitle("Proportion Surface Water vs. Change in Residential Use") +xlab("Proportion Surface Water") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("propsurf.png")
#proprecyc
ggplot(data=wd.dat.3reg,aes(x=proprecyc,y=changer,col=region2)) + geom_point() +geom_smooth(method=lm,se=FALSE) + ggtitle("Proportion Recycled Water vs. Change in Residential Use") +xlab("Proportion Recycled Water") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("proprecyc.png")
#propimport
ggplot(data=wd.dat.3reg,aes(x=propimport,y=changer,col=region2)) + geom_point() +geom_smooth(method=lm,se=FALSE) + ggtitle("Proportion Imported Water vs. Change in Residential Use") +xlab("Proportion Surface Water") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("propimport.png")
#medinc
ggplot(data=wd.dat.3reg,aes(x=medinc,y=changer,col=region2)) + geom_point() +geom_smooth(method=lm,se=FALSE) + ggtitle("Median Income vs. Change in Residential Use") +xlab("Median Household Income (Thousands USD)") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("medianincome.png")
#rgpcd10
ggplot(data=wd.dat.3reg,aes(x=rgpcd10,y=changer,col=region2)) + geom_point() +geom_smooth(method=lm,se=FALSE) + ggtitle("Residential Use 2010 vs. Change in Residential Use") +xlab("Residential Use (GPCD) 2010") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("residentialuse2010.png")


#Categorial/Binary variables- boxplots
#groundwater sources
ggplot(data=wd.dat.3reg,aes(factor(ground),changer,col=region2)) + geom_boxplot() +ggtitle("Number of Groundwater Sources vs. Change in Residential Use") +xlab("Number of Groundwater Sources") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("groundwatersources.png")
#surface water sources
ggplot(data=wd.dat.3reg,aes(factor(surf),changer,col=region2)) + geom_boxplot() +ggtitle("Number of Groundwater Sources vs. Change in Residential Use") +xlab("Number of Groundwater Sources") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("surfacewatersources.png")
#number of imported sources
ggplot(data=wd.dat.3reg,aes(factor(imported),changer,col=region2)) + geom_boxplot() +ggtitle("Number of Imported Water Sources vs. Change in Residential Use") +xlab("Number of Imported Water Sources") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("importedsources.png")

# Total number of sources
ggplot(data=wd.dat.3reg,aes(factor(tot.source),changer,col=region2)) + geom_boxplot() +ggtitle("Number of Total Water Sources vs. Change in Residential Use") +xlab("Number of Imported Water Sources") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("totalsources.png")


#recyled (binary)
ggplot(data=wd.dat.3reg,aes(factor(recycled),changer,col=region2)) + geom_boxplot() +ggtitle("Recycled Water vs. Change in Residential Use") +xlab("Use of Recycled Water (No/Yes)") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("recycled.png")
#desalination (binary)
ggplot(data=wd.dat.3reg,aes(factor(desal),changer,col=region2)) + geom_boxplot() +ggtitle("Desalination vs. Change in Residential Use") +xlab("Use of Desalinated Water (No/Yes)") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("desal.png")

# Nesting attributes
# buyer tier
ggplot(data=na.omit(wd.dat.3reg),aes(factor(buyertier),changer,col=region2)) + geom_boxplot() +ggtitle("Buyer Tier vs. Change in Residential Use") +xlab("Buyer Tier (Levels Below in the Tree)") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("buyertier.png")

#seller tier
ggplot(data=na.omit(wd.dat.3reg),aes(factor(sellertier),changer,col=region2)) + geom_boxplot() +ggtitle("Seller Tier vs. Change in Residential Use") +xlab("Seller Tier (Levels Above in the Tree)") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("sellertier.png")
# selltier <- aov(changer ~ factor(sellertier),data=wd.dat.3reg[wd.dat.3reg$region2=="South",])
# summary(selltier)
# TukeyHSD(selltier)

# both regions combined
ggplot(data=na.omit(wd.dat.3reg),aes(factor(sellertier),changer)) + geom_boxplot() +ggtitle("Seller Tier vs. Change in Residential Use") +xlab("Seller Tier (Levels Above in the Tree)") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("sellertier_regions_comb.png")

#direct buyers
ggplot(data=wd.dat.3reg,aes(x=buyers,y=changer,col=region2)) + geom_point() +geom_smooth(method=lm,se=FALSE) + ggtitle("Direct Buyers vs. Change in Residential Use") +xlab("Number of Direct Buyers") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("directbuyers.png")

#direct sellers
ggplot(data=na.omit(wd.dat.3reg),aes(factor(sellers),changer,col=region2)) + geom_boxplot() +ggtitle("Direct Sellers vs. Change in Residential Use") +xlab("Number of Direct Sellers") +ylab("% Change in Residential Use (GPCD)")+geom_hline(yintercept=0,linetype=2)
#ggsave("directsellers.png")

```

North vs. South vs. Central Valley boxplots

```{r north south plots}
# Use in 2010, Regions
ggplot(data=na.omit(wd.dat.3reg),aes(region2,rgpcd10,col=region2)) + geom_boxplot() +ggtitle("2010 Residential Use by Region") +xlab("Region") +ylab("Residential Use, 2010 (GPCD)")
#ggsave("Use_2010.png")
use.reg <- aov(rgpcd10~region2,data=wd.dat.3reg) # ANOVA for significance
summary(use.reg) 
TukeyHSD(use.reg) # Tukey Honest sig differences between groups

# Median income, Regions
ggplot(data=na.omit(wd.dat.3reg),aes(region2,medinc,col=region2)) + geom_boxplot() +ggtitle("Median Income by Region") +xlab("Region") +ylab("Median Income (1000s USD)")
#ggsave("North_South_Income.png")
medinc.reg <- aov(medinc~region2,data=wd.dat.3reg) # ANOVA for significance
summary(medinc.reg) 
TukeyHSD(medinc.reg) # Tukey Honest sig differences between groups

# Severity by region
ggplot(data=na.omit(wd.dat.3reg),aes(region2,severity,col=region2)) + geom_boxplot() +ggtitle("Drought Severity by Region") +xlab("Region") +ylab("Drought Severity (Weeks at or above Drought Monitor 3")
#ggsave("severity_north_south.png")
sev.reg <- aov(severity~region2,data=wd.dat.3reg) # ANOVA for significance
summary(sev.reg) 
TukeyHSD(sev.reg) # Tukey Honest sig differences between groups

summary(lm(changer~severity,data=wd.dat.3reg))

# Change in Use,Regions
ggplot(data=na.omit(wd.dat.3reg),aes(region2,changer,col=region2)) + geom_boxplot() +ggtitle("Change in Use by Region") +xlab("Region") +ylab("Change in Residential Use, 2010-2015 (GPCD)")
#ggsave("Use_2010.png")
changer.reg <- aov(changer~region2,data=wd.dat.3reg) # ANOVA for significance
summary(changer.reg) 
TukeyHSD(changer.reg) # Tukey Honest sig differences between groups

# Seller Tier, Regions
ggplot(data=na.omit(wd.dat.3reg),aes(region2,sellertier,col=region2)) + geom_boxplot() +ggtitle("Seller Tier by Region") +xlab("Region") +ylab("Seller Tier by Region")
#ggsave("Use_2010.png")
selltier.reg <- aov(sellertier~region2,data=wd.dat.3reg) # ANOVA for significance
summary(selltier.reg) 
TukeyHSD(selltier.reg) # Tukey Honest sig differences between groups

```

By adjudication status (groundwater, and change in use)

Normal linear models

```{r linear models}
summary(lm(changer~medinc+region2+rgpcd10+sellertier,data=wd.dat.3reg))
summary(lm(changer~medinc+region2+rgpcd10+severity,data=wd.dat.3reg))
summary(lm(changer~medinc+region2+rgpcd10+severity+rgpcd10*region2,data=wd.dat.3reg))
summary(lm(changer~medinc+region2+rgpcd10+severity+rgpcd10*region2+severity*region2,data=wd.dat.3reg))
summary(lm(changer~medinc+region2+rgpcd10+severity+simpson+propdesal+propground+propimport+proprecyc+propsurf,data=wd.dat.3reg))
summary(lm(changer~medinc+region2+rgpcd10+severity+rgpcd10*region2+severity*region2+medinc*region2,data=wd.dat.3reg))

# without regions
summary(lm(changer~medinc+rgpcd10+sellertier+severity,data=wd.dat.3reg))
summary(lm(changer~medinc+rgpcd10+severity+simpson+propdesal+propground+propimport+proprecyc+propsurf,data=wd.dat.3reg))

```


